### ISSUE TITLE
dlint.sh

### ISSUE THREAD

**Issue by rockysui** [ksen007/jalangi2analyses#5]
Hi Liang,

A typo in your script "dlint.sh" when I was trying to run the analysis in a browser using proxy.
The missing of "--analysis" leads to incomplete inputs to jalangi.

line 19 
replaceStr='../../jalangi2analyses/src’ ==>
replaceStr=‘—analysis ../../jalangi2analyses/src’

 line 26 
replaceStr='../src'==>
replaceStr=‘—analysis ../../jalangi2analyses/src’

**Comment by JacksonGL** [comment]
Thanks for reporting this issue. The problem seems to be caused by a recent change in Jalangi2.
Please ignore `dlint.sh` and do the following things:
1. run `git pull` to grab a fix change
2. use `run.js` command to run dlint as shown on the [usage section of the project homepage](https://github.com/ksen007/jalangi2analyses#usage).
